### PR TITLE
fix for unsafe on windows

### PR DESCRIPTION
**Pull request by edewit**
The photo url has a source that starts with "///" that is considered unsafe by angular added to sanitation white list

### CODE REVIEW

**Comment by matzew** [comment]
@sebastienblanc any comment ?

**Comment by sebastienblanc** [comment]
:+1: I can see the picture now

**Comment by secondsun** [comment]
How do I test this? (IE what is the bug being fixed, what behavior should I see, what prerequisites do I need to run it)

**Comment by edewit** [comment]
the preview of the camera picture that was taken is not shown because it's marked as unsafe by angular after this fix you should see the picture again

**Comment by secondsun** [comment]
So I don't know how to get the project building on Windows and the README isn't particularly helpful.  Could you give that a quick update as well?

**Comment by edewit** [comment]
`cordova emulate wp8` for emulator or `cordova run wp8` or open the generated project in the platform directory and hit run in visual studio

**Comment by secondsun** [comment]
@edewit Thanhks.  I'll test it when I'm back at my desktop.

**Comment by secondsun** [comment]
Ok I see the picture :)

**Comment by abstractj** [comment]
@edewit after the positive feedback from @sebastienblanc and @secondsun I'm merging it, but let me know if something is wrong.

Landed!

**Pull request closed without merging**
