### PR TITLE
also add file

### PR DESCRIPTION
**Pull request by edewit**
trying to fix this for windows introduced a problem for android and ios the image taken from the camera was no longer displayed see [AGCORDOVA-75](https://issues.jboss.org/browse/AGCORDOVA-75)

### CODE REVIEW

**Comment by edewit** [comment]
@danielpassos fixed it

**Comment by corinnekrych** [comment]
+1
Tested on iOS, with this fix the image is displayed on screen

**Comment by danielpassos** [comment]
:+1:

**Comment by danielpassos** [comment]
Landed at 30f93f2384299d38a94a66175f979dc5f4a9658e

**Pull request closed without merging**
