### PR TITLE
Improve Shoot README

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
@edewit @abstractj Could you give it a spin and test the Android setup instructions?

**Comment by edewit** [comment]
:+1:

**Comment by abstractj** [comment]
@danielpassos will do next week.

**Comment by abstractj** [comment]
@danielpassos I think what have you done is pretty much the work landed on https://issues.jboss.org/browse/AGCORDOVA-68 nope?

**Comment by danielpassos** [comment]
@abstractj Yes, let me rebase and remove the commit https://github.com/danielpassos/aerogear-cordova-cookbook/commit/c6a7a9cdbecfff3b6f972f0126fe48c84251db97

**Comment by danielpassos** [comment]
Done!

**Comment by abstractj** [comment]
@danielpassos landed, thank you

**Pull request merged**
